Play travis
Otus-DevOps-2020-05/prettypineapple_infra pull request #1
Opened 2020-06-16 13:43 UTC by prettypineapple

2020-06-17 06:22 UTC, mrgreyves requested changes
Здравствуйте!) Нужно добавить описание к вашему пр, возвращаю на доработку.
![image](https://user-images.githubusercontent.com/34331259/84862595-1b610d80-b07c-11ea-9ee3-b6b830fcaf25.png)

2020-06-17 09:39 UTC, prettypineapple commented
Обновила описание пулл-реквеста

2020-06-18 05:41 UTC, mrgreyves approved these changes
Здравствуйте!) ДЗ выполнено корректно, апрув!)

2020-06-18 05:41 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 2)
🤘🤘🤘

2020-06-18 08:38 UTC, merged